[package]
name = "faster-api"
version = "0.1.0"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
edition = "2018"

[lib]
name = "faster"
crate-type = ["cdylib", "staticlib"]

[dependencies]
faster-rs = "0.11.0"
libc = "0.2.80"

